In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder

pd.set_option('display.max_rows', None) # zeigt alle spalten an

In [2]:
data = pd.read_csv('sales.csv')

In [3]:
data.columns = [column.lower() for column in data.columns]
data.columns = data.columns.str.replace(" ","_")
data = data.drop(['unnamed:_0'],axis=1)

data.head()

unnamed:_0  store_id  day_of_week        date  nb_customers_on_day  open  \
0      425390       366            4  2013-04-18                  517     1   
1      291687       394            6  2015-04-11                  694     1   
2      411278       807            4  2013-08-29                  970     1   
3      664714       802            2  2013-05-28                  473     1   
4      540835       726            4  2013-10-10                 1068     1   

   promotion state_holiday  school_holiday  sales  
0          0             0               0   4422  
1          0             0               0   8297  
2          1             0               0   9729  
3          1             0               0   6513  
4          1             0               0  10882

In [ ]:
data.head()

In [7]:
data = data.drop(['unnamed:_0'],axis=1)


In [ ]:
# object: stor_id, day of week, costum, opebn , promo, state holid, school sales

In [8]:
data.head()

store_id  day_of_week        date  nb_customers_on_day  open  promotion  \
0       366            4  2013-04-18                  517     1          0   
1       394            6  2015-04-11                  694     1          0   
2       807            4  2013-08-29                  970     1          1   
3       802            2  2013-05-28                  473     1          1   
4       726            4  2013-10-10                 1068     1          1   

  state_holiday  school_holiday  sales  
0             0               0   4422  
1             0               0   8297  
2             0               0   9729  
3             0               0   6513  
4             0               0  10882

In [70]:
# data[data.open!=1&data.store_ID]

In [71]:
# data.pivot_table(index=(data.store_ID,data.day_of_week,data.date))

KeyboardInterrupt: 

In [9]:
num = data['nb_customers_on_day']
cat = data[['store_id','day_of_week','open','promotion','state_holiday','school_holiday']]
target = data['sales']

In [10]:
cat = cat.astype(object)

In [11]:
feat = pd.concat([num,cat],axis=1)

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(feat, target, test_size=0.3)

In [13]:
from sklearn.preprocessing import MinMaxScaler
num_train = X_train.select_dtypes(np.number)
num_test = X_test.select_dtypes(np.number)

In [14]:
transformer = MinMaxScaler().fit(num_train)
num_train_minmax = transformer.transform(num_train)
num_test_minmax = transformer.transform(num_test)

num_train_minmax = pd.DataFrame(num_train_minmax)
num_test_minmax = pd.DataFrame(num_test_minmax)

In [15]:
# num_test_minmax

In [16]:
from sklearn.preprocessing import OneHotEncoder

cat_train = X_train.select_dtypes(object)
cat_test = X_test.select_dtypes(object)

ohe = OneHotEncoder(handle_unknown='error', drop='first').fit(cat_train) 
# handle_unknown='error' fuer unvorhergesehene kategorien
cat_train_ohe = ohe.transform(cat_train).toarray()
cat_test_ohe = ohe.transform(cat_test).toarray()


cat_train_ohe = pd.DataFrame(cat_train_ohe)
cat_test_ohe = pd.DataFrame(cat_test_ohe)
pd.DataFrame(cat_train_ohe).head()

0     1     2     3     4     5     6     7     8     9     ...  1116  \
0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

   1117  1118  1119  1120  1121  1122  1123  1124  1125  
0   0.0   1.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0  
1   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   1.0  
2   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0  
3   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0  
4   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0  

[5 rows x 1126 columns]

In [17]:
X_train = pd.concat([num_train_minmax,cat_train_ohe],axis=1)
X_test = pd.concat([num_test_minmax,cat_test_ohe],axis=1)

In [21]:
# X_train

In [22]:
# from sklearn.ensemble import RandomForestRegressor

In [24]:
# regressor = RandomForestRegressor(max_depth=5, # max number of questions
#                              min_samples_split=20, # amount of rows still considered at every question
#                              min_samples_leaf =20, # ultimate answer based on at least this many rows
#                              max_samples=0.8) # fraction of original dataset

In [ ]:
# regressor.fit(X_train, y_train)

In [27]:
# %%time
# pred = regressor.predict(X_test)

In [36]:
# pred

array([4673.29018338, 8861.74122697, 7579.96215888, ..., 7579.96215888,
       5624.7219301 , 5538.05027983])

In [25]:
# target

In [26]:
# pd.DataFrame({'predictions':pred,'sales':y_test})

In [ ]:
# pd.DataFrame([X_test,pred])

In [18]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_squared_log_error

# rms = mean_squared_error(y_test, pred, squared=False)
# rms

In [28]:
# rmsle = mean_squared_log_error(y_test, pred, squared=False)
# rmsle

In [29]:
# regressor.score(X_train, y_train)

In [30]:
# regressor.score(X_test, y_test)

In [32]:
# # model pipeline
# from sklearn.model_selection import cross_val_score

# model1 = DecisionTreeRegressor()

# from sklearn.linear_model import LinearRegression
# model2 = LinearRegression()

# from sklearn.neighbors import KNeighborsRegressor
# model3 = KNeighborsRegressor()


# model_pipeline = [model1, model2, model3]
# model_names = ['Decision Tree Regressor', 'Linear Regression', 'KNN']
# scores = {}
# for model, model_name in zip(model_pipeline, model_names):
#     mean_score = np.mean(cross_val_score(model, X_train_minmax, y_train, cv=5))
#     scores[model_name] = mean_score
# print(scores)


In [47]:
from sklearn.linear_model import LinearRegression
model2 = LinearRegression()

In [48]:
model2.fit(X_train, y_train)

LinearRegression()

In [51]:
%%time
pred = model2.predict(X_test)
pred

array([ 4756.01925872, 10099.31724514,  5857.91839049, ...,
        6949.46241734,  4113.67827766,  5726.36615794])

In [52]:
rms = mean_squared_error(y_test, pred, squared=False)
rms

814.5497190555026

In [19]:

from sklearn.neighbors import KNeighborsRegressor
model3 = KNeighborsRegressor()

model3.fit(X_train, y_train)


KNeighborsRegressor()

In [34]:
%%time
pred = model3.predict(X_test)
pred

CPU times: total: 2h 34min 7s
Wall time: 14min 35s


array([ 9241.6,  4274.2,  4968.6, ..., 12389.4,  4975.2,  7193.8])

In [35]:
rms = mean_squared_error(y_test, pred, squared=False)
rms

801.2233189933091

In [61]:
# %%time
# from sklearn.tree import DecisionTreeRegressor
# model4 = DecisionTreeRegressor()
# model4.fit(X_train, y_train)

DecisionTreeRegressor()

In [62]:
# %%time
# pred = model4.predict(X_test)
# pred

CPU times: total: 1.44 s
Wall time: 1.45 s


array([ 4003., 10798.,  5191., ...,  6618.,  3295.,  6034.])

In [63]:
# rms = mean_squared_error(y_test, pred, squared=False)
# rms

809.4919246318176

In [64]:
# model4.score(X_test, y_test)

0.9555868219463651

In [69]:
# %%time 
# # AdaBoostRegressor
# from sklearn.ensemble import AdaBoostRegressor
# model5 = AdaBoostRegressor() 
# model5.fit(X_train, y_train)
# pred = model5.predict(X_test)
# rms = mean_squared_error(y_test, pred, squared=False)
# rms

CPU times: total: 12min 33s
Wall time: 12min 33s


1741.0779705710052

In [ ]:
# %%time # error message for LogisticRegression
# from sklearn.linear_model import LogisticRegression
# model6 = LogisticRegression() 
# model6.fit(X_train, y_train)
# pred = model6.predict(X_test)
# rms = mean_squared_error(y_test, pred, squared=False)
# rms

In [1]:
# %%time 
# # MLPRegressor
# from sklearn.neural_network import MLPRegressor
# model7 = MLPRegressor() 
# model7.fit(X_train, y_train)
# pred = model7.predict(X_test)
# rms = mean_squared_error(y_test, pred, squared=False)
# rms

In [70]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor()

In [ ]:
%%time
# hyperparameter
# from sklearn.model_selection import RandomizedSearchCV
# from sklearn.neighbors import KNeighborsRegressor
# model = KNeighborsRegressor()

weights_choices = ['uniform', 'distance']
algorithm_choices = ['auto','ball_tree','kd_tree','brute']
leaf_size_choices = [10,20,30,40,50]
p_choices = [1,2]

random_grid = {'weights': weights_choices,
               'algorithm': algorithm_choices,
               'leaf_size': leaf_size_choices,
               'p': p_choices}


grid_search = RandomizedSearchCV(estimator = model, param_distributions = random_grid, cv = 5)
grid_search.fit(X_train, y_train)
grid_search.best_params_

In [35]:
new = pd.read_csv('validation_for_students.csv')
new.head()

True_index  Store_ID  Day_of_week        Date  Nb_customers_on_day  Open  \
0           7       764            4  2013-12-26                    0     0   
1          19        22            3  2013-05-22                  449     1   
2          31      1087            6  2013-06-29                  622     1   
3          45       139            6  2013-08-17                  314     1   
4          56       568            1  2014-04-07                  356     1   

   Promotion State_holiday  School_holiday  
0          0             c               1  
1          0             0               1  
2          0             0               0  
3          0             0               0  
4          0             0               0

In [36]:
new = new.drop(['True_index'],axis=1)
new = new.drop(['Date'],axis=1)

In [39]:
new.head()

Store_ID  Day_of_week  Nb_customers_on_day  Open  Promotion State_holiday  \
0       764            4                    0     0          0             c   
1        22            3                  449     1          0             0   
2      1087            6                  622     1          0             0   
3       139            6                  314     1          0             0   
4       568            1                  356     1          0             0   

   School_holiday  
0               1  
1               1  
2               0  
3               0  
4               0

In [46]:

# new.columns = [column.lower() for column in data.columns]
# new.columns = data.columns.str.replace(" ","_")
# new = new.drop(['Date'],axis=1)
# new = new.drop(['True_index'],axis=1)
# new = new.drop(['Unnamed: 0'],axis=1)
# new.columns = [column.lower() for column in data.columns]
# new.columns = new.columns.str.replace(" ","_")
new_2 = new

In [47]:
new_2.head()

Store_ID  Day_of_week  Nb_customers_on_day  Open  Promotion State_holiday  \
0       764            4                    0     0          0             c   
1        22            3                  449     1          0             0   
2      1087            6                  622     1          0             0   
3       139            6                  314     1          0             0   
4       568            1                  356     1          0             0   

   School_holiday  
0               1  
1               1  
2               0  
3               0  
4               0

In [49]:

new_2.columns = [column.lower() for column in new_2.columns]
new_2.columns = new_2.columns.str.replace(" ","_")
new_2.head()

store_id  day_of_week  nb_customers_on_day  open  promotion state_holiday  \
0       764            4                    0     0          0             c   
1        22            3                  449     1          0             0   
2      1087            6                  622     1          0             0   
3       139            6                  314     1          0             0   
4       568            1                  356     1          0             0   

   school_holiday  
0               1  
1               1  
2               0  
3               0  
4               0

In [52]:
%%time

num = new['nb_customers_on_day']
cat = new[['store_id','day_of_week','open','promotion','state_holiday','school_holiday']]
# target = new['sales']
cat = cat.astype(object)

CPU times: total: 46.9 ms
Wall time: 36 ms


In [53]:
len(num)
feat = pd.concat([num,cat],axis=1)

In [95]:
feat.head()

Nb_customers_on_day Store_ID Day_of_week Open Promotion State_holiday  \
0                    0      764           4    0         0             c   
1                  449       22           3    1         0             0   
2                  622     1087           6    1         0             0   
3                  314      139           6    1         0             0   
4                  356      568           1    1         0             0   

  School_holiday  
0              1  
1              1  
2              0  
3              0  
4              0

In [54]:
num = feat.select_dtypes(np.number)
cat = feat.select_dtypes(np.object)

C:\Users\Martin\AppData\Local\Temp\ipykernel_1192\1304581886.py:2: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  cat = feat.select_dtypes(np.object)


In [55]:
new_minmax = transformer.transform(num)

In [56]:
new_ohe = ohe.transform(cat).toarray()

In [58]:
%% time
new_minmax = pd.DataFrame(new_minmax)
new_ohe = pd.DataFrame(new_ohe)

new_normal = pd.concat([new_minmax,new_ohe],axis=1)

pred = model3.predict(new_normal)

# print(mean_squared_error(y_test, pred, squared=False))
print(pred)

[    0.   3642.6  6041.4 ... 10682.2  2631.8  5664. ]


In [62]:
true_in = pd.read_csv('validation_for_students.csv')

In [63]:
final = pd.DataFrame({'True_index':true_in.True_index,'Sales':pred})

In [68]:
len(final)

71205

In [67]:
final.to_csv('beavis_knreg.csv')